-- Crie chaves estrangeiras para a tabela TB_PEDIDO:
-- com TB_Cliente e TB_Vendedor
ALTER TABLE tb_Pedido
ADD FOREIGN KEY (CODCLI) REFERENCES tb_Cliente(CODCLI);

ALTER TABLE tb_Pedido
ADD FOREIGN KEY (CODVEN) REFERENCES tb_Vendedor(CODVEN);

-- Crie Chaves estrangeiras para a tabela TB_PRODUTO
-- com TB_TIPOPRODUTO e com TB_UNIDADE
ALTER TABLE TB_PRODUTO
ADD FOREIGN KEY (COD_TIPO) REFERENCES TB_TIPOPRODUTO(COD_TIPO);

ALTER TABLE TB_PRODUTO
ADD FOREIGN KEY (COD_UNIDADE) REFERENCES TB_UNIDADE(COD_UNIDADE);


-- Crie chaves estrangeiras para a tabela TB_ITENSPEDIDO:
-- com TB_PEDIDO, TB_PRODUTO e TB_COR.
ALTER TABLE TB_ITENSPEDIDO
ADD FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PEDIDO(NUM_PEDIDO);

ALTER TABLE TB_ITENSPEDIDO
ADD FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO);

ALTER TABLE TB_ITENSPEDIDO
ADD FOREIGN KEY (CODCOR) REFERENCES TB_COR(CODCOR);

-- Crie uma chave única para o campo UNIDADE na tabela TB_UNIDADE;
ALTER TABLE TB_UNIDADE
ADD CONSTRAINT UK_UNIDADE UNIQUE (UNIDADE);

-- Crie uma chave única para o campo TIPO da tabela TB_TIPOPRODUTO;
ALTER TABLE TB_TIPOPRODUTO
ADD CONSTRAINT UK_TIPO UNIQUE (TIPO);


--Crie Constraints CHECK para a tabela TB_PRODUTO
-- o preço de venda não pode ser menor que o preço de custo
-- o preco de custo precisa ser maior que zero
-- o campo QTD_REAL não pode ser menor que zero.
ALTER TABLE TB_PRODUTO
ADD CONSTRAINT CHK_PRECO
CHECK (PRECO_VENDA >= PRECO_CUSTO AND PRECO_CUSTO > 0 AND QTD_REAL >= 0);


--Crie Constraints CHECK para a tabela TB_ITENSPEDIDO
-- o campo QUANTIDADE deve ser maior ou igual a um;
ALTER TABLE TB_ITENSPEDIDO
ADD CONSTRAINT CHK_QTD
CHECK (QUANTIDADE >= 1);
-- o campo PR_UNITARIO deve ser maior que zero;
ALTER TABLE TB_ITENSPEDIDO
ADD CONSTRAINT CHK_QTDPR
CHECK (PR_UNITARIO >= 1);
-- o campo DESCONTO não pode ser menor que zero e maior que 10;
ALTER TABLE TB_ITENSPEDIDO
ADD CONSTRAINT CHK_DESC
CHECK (DESCONTO >=1 AND DESCONTO <= 10)

-- Crie valores default para TB_PRODUTO, considerando.
-- Zero para PRECO_CUSTO e PRECO_VENDA;
ALTER TABLE TB_PRODUTO
ADD CONSTRAINT PRECO_CUSTO DEFAULT 0 FOR PRECO_CUSTO 

ALTER TABLE TB_PRODUTO
ADD CONSTRAINT PRECO_VENDA DEFAULT 0 FOR PRECO_VENDA
-- Zero para QTD_REAL, QTD_MINIMA e QTD_ESTIMADA;
ALTER TABLE TB_PRODUTO
ADD CONSTRAINT QTD_REAL DEFAULT 0 FOR QTD_REAL

ALTER TABLE TB_PRODUTO
ADD CONSTRAINT QTD_MINIMA DEFAULT 0 FOR QTD_MINIMA

ALTER TABLE TB_PRODUTO
ADD CONSTRAINT QTD_ESTIMADA DEFAULT 0 FOR QTD_ESTIMADA
-- Zero para COD_TIPO e COD_UNIDADE;
ALTER TABLE TB_PRODUTO
ADD CONSTRAINT COD_TIPO DEFAULT 0 FOR COD_TIPO

ALTER TABLE TB_PRODUTO
ADD CONSTRAINT COD_UNIDADE DEFAULT 0 FOR COD_UNIDADE;












